### ISSUE TITLE
FC13: En tant que développeur je dois faire le prototype statique (html/css) de l’application

### ISSUE THREAD

**Issue by JosephKhalifeETS** [gti525/h18-gestion-salle#1]
En tant que développeur je dois faire le prototype statique (html/css) de l’application

**Comment by cathlejo** [comment]
assistance du dash --> mettre en rouge
avoir un bouton modifier pour options + paramètres dans salle
modifier le check box pour supprimer une salle --> à droite de la salle
modification du log off --> changer l'icone
